//! Report export functionality — HTML, CSV, and Markdown export
//! for simulation results and measurement data.

use crate::app::NekoSpiceApp;

impl NekoSpiceApp {
    /// Export simulation report as HTML file.
    pub(crate) fn export_report_html(&mut self) {
        let Some(run) = &self.simulation_panel.last_run else {
            self.status_message = Some("No simulation run to export".to_string());
            return;
        };
        let html = osl_sim::run_report_html(&run.metadata);
        let path = run.output_dir.join("report.html");
        match std::fs::write(&path, &html) {
            Ok(()) => self.status_message = Some(format!("HTML report saved: {}", path.display())),
            Err(e) => self.status_message = Some(format!("HTML export failed: {}", e)),
        }
    }

    /// Export measurement data as CSV file.
    pub(crate) fn export_measurements_csv(&mut self) {
        let Some(run) = &self.simulation_panel.last_run else {
            self.status_message = Some("No simulation run to export".to_string());
            return;
        };
        let crate::waveform_summary::GuiWaveformSummaryState::Ready(summary) = &run.waveform else {
            self.status_message = Some("No waveform data to export".to_string());
            return;
        };

        let mut csv = String::from("Signal,Unit,Samples,First,Last,Min,Max,Avg,RMS,P-P\n");
        for v in &summary.variables {
            csv.push_str(&format!(
                "{},{},{},{},{},{},{},{},{},{}\n",
                v.name,
                v.unit,
                v.samples,
                v.first,
                v.last,
                v.min,
                v.max,
                v.avg,
                v.rms,
                v.peak_to_peak,
            ));
        }

        let path = run.output_dir.join("measurements.csv");
        match std::fs::write(&path, &csv) {
            Ok(()) => self.status_message = Some(format!("CSV saved: {}", path.display())),
            Err(e) => self.status_message = Some(format!("CSV export failed: {}", e)),
        }
    }

    /// Export simulation report as Markdown file.
    pub(crate) fn export_report_markdown(&mut self) {
        let Some(run) = &self.simulation_panel.last_run else {
            self.status_message = Some("No simulation run to export".to_string());
            return;
        };

        let status = run.metadata.status.as_str();
        let duration = run.metadata.duration_ms;
        let backend = &run.metadata.backend;

        let mut md = String::new();
        md.push_str("# NekoSpice Simulation Report\n\n");
        md.push_str(&format!("**Status**: {}  \n", status));
        md.push_str(&format!("**Duration**: {} ms  \n", duration));
        md.push_str(&format!("**Backend**: {}  \n", backend));
        md.push_str(&format!("**Run ID**: {}  \n\n", run.metadata.run_id));

        // Waveform summary
        if let crate::waveform_summary::GuiWaveformSummaryState::Ready(summary) = &run.waveform {
            md.push_str("## Waveform Summary\n\n");
            md.push_str(&format!("**Points**: {}  \n", summary.point_count));
            md.push_str(&format!("**Variables**: {}  \n\n", summary.variable_count));
            md.push_str("| Signal | Unit | Min | Max | Avg | RMS | P-P |\n");
            md.push_str("|--------|------|-----|-----|-----|-----|-----|\n");
            for v in &summary.variables {
                md.push_str(&format!(
                    "| {} | {} | {:.4} | {:.4} | {:.4} | {:.4} | {:.4} |\n",
                    v.name, v.unit, v.min, v.max, v.avg, v.rms, v.peak_to_peak,
                ));
            }
        }

        md.push_str("\n---\n*Generated by NekoSpice*\n");

        let path = run.output_dir.join("report.md");
        match std::fs::write(&path, &md) {
            Ok(()) => self.status_message = Some(format!("Markdown report: {}", path.display())),
            Err(e) => self.status_message = Some(format!("Markdown export failed: {}", e)),
        }
    }
}
