use super::NekoSpiceApp;
use osl_kicad::KicadIndexedSymbol;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct LibraryFilter {
    pub(super) name: String,
    pub(super) count: usize,
}

impl NekoSpiceApp {
    pub(super) fn library_filters(&self) -> Vec<LibraryFilter> {
        let Some(library) = &self.library else {
            return vec![LibraryFilter {
                name: "All".to_string(),
                count: 0,
            }];
        };
        let mut filters = vec![LibraryFilter {
            name: "All".to_string(),
            count: library.index().symbols.len(),
        }];
        filters.extend(
            library
                .index()
                .libraries
                .iter()
                .map(|library| LibraryFilter {
                    name: library.name.clone(),
                    count: library.symbol_count,
                }),
        );
        filters
    }

    pub(super) fn filtered_library_symbols(&self) -> Vec<KicadIndexedSymbol> {
        self.library
            .as_ref()
            .map(|library| library.filtered_index(&self.symbol_search).symbols)
            .unwrap_or_default()
    }

    pub(super) fn selected_library_symbol_snapshot(&self) -> Option<KicadIndexedSymbol> {
        let symbol_id = self.selected_symbol_id.as_deref()?;
        self.library
            .as_ref()
            .and_then(|library| library.symbol(symbol_id))
            .cloned()
    }
}

pub(super) fn spice_preview_lines(symbol: &KicadIndexedSymbol) -> Vec<String> {
    let pin_numbers = symbol
        .pins
        .iter()
        .map(|pin| pin.number.as_str())
        .collect::<Vec<_>>();
    let pins = if pin_numbers.is_empty() {
        "1 2".to_string()
    } else {
        pin_numbers.join(" ")
    };
    vec![
        format!("* {}", symbol.id),
        format!(
            "* {}",
            symbol.description.as_deref().unwrap_or(&symbol.name)
        ),
        format!(".subckt {} {}", symbol.name, pins),
        "* KiCad symbol preview generated by NekoSpice".to_string(),
        "* Replace this stub with the vendor SPICE model when available.".to_string(),
        format!("* Source: {}", symbol.source),
        format!(".ends {}", symbol.name),
    ]
}
