//! 国际化框架。定义 [`UiText`] 枚举和中英文翻译实现。
//!
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub(super) enum StudioLocale {
    #[default]
    English,
    SimplifiedChinese,
}

impl StudioLocale {
    pub(super) const ALL: [Self; 2] = [Self::English, Self::SimplifiedChinese];

    /// native name。
    pub(super) fn native_name(self) -> &'static str {
        match self {
            Self::English => "English",
            Self::SimplifiedChinese => "简体中文",
        }
    }

    /// short code。
    pub(super) fn short_code(self) -> &'static str {
        match self {
            Self::English => "EN",
            Self::SimplifiedChinese => "中",
        }
    }

    /// next。
    pub(super) fn next(self) -> Self {
        match self {
            Self::English => Self::SimplifiedChinese,
            Self::SimplifiedChinese => Self::English,
        }
    }

    /// text。
    pub(super) fn text(self, key: UiText) -> &'static str {
        match self {
            Self::English => key.en(),
            Self::SimplifiedChinese => key.zh_hans(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(dead_code)]
pub(super) enum UiText {
    ActiveProject,
    AiAssistant,
    AnalysisStatus,
    AnalysisSetup,
    Appearance,
    Appendix,
    Artifacts,
    AskCircuit,
    AssistantPrompt,
    AutoScale,
    Average,
    Backend,
    BaselineRun,
    Body,
    BodePlot,
    Bounds,
    Buses,
    ApplyProperties,
    CanvasLinked,
    ComponentParameters,
    CandidateResults,
    Category,
    CheckLoopStability,
    Clean,
    CommandCenter,
    CoverPage,
    CrossProbe,
    CriticalFailures,
    Constraints,
    CurrentLanguage,
    CurrentTheme,
    Drc,
    DeleteSelected,
    Diagnostics,
    Dirty,
    Document,
    DesignChecklist,
    DesignReview,
    Distributions,
    Edit,
    ExplainWaveform,
    ExportReport,
    ExportCsv,
    ExportHistory,
    ExportShare,
    ExportWaveforms,
    Fit,
    FitHint,
    FindOptimization,
    FftAnalysis,
    FormulaEditor,
    Graphics,
    Groups,
    HealthReady,
    HighThd,
    HomeSubtitle,
    HomeTitle,
    ImportKiCad,
    ImportMeasurementData,
    Impact,
    Info,
    Insights,
    Inspector,
    JobMonitor,
    KiCadInspector,
    Kind,
    Label,
    LastRun,
    LastValue,
    Labels,
    Language,
    Libraries,
    LibrarySearchHint,
    LibraryScope,
    LibraryStatus,
    LiveMeasurements,
    LoadSymbols,
    LoopStability,
    Matches,
    MeasurementNoise,
    Measurements,
    Missing,
    ModelUpdateAvailable,
    ModelLibrary,
    ModelParameters,
    ModelLibraryCaption,
    ModelPreview,
    ModelSummary,
    MonteCarlo,
    MoreVariables,
    NewProject,
    NewSchematic,
    NoiseAnalysis,
    Issues,
    NoDiagnostics,
    NoDocument,
    NoEditableSchematicLoaded,
    NoLibraryLoaded,
    NoProject,
    NoRecentRun,
    NoSchematicLoaded,
    NoSelectedItem,
    NoSelection,
    NoWaveform,
    Netlist,
    NetlistPreview,
    NextSteps,
    Open,
    OpenHint,
    OpenSchematic,
    OpenIssues,
    OpenProject,
    Optimization,
    OptimizationCaption,
    OptimizationStudio,
    Objective,
    OutputArtifacts,
    Overview,
    PageSize,
    ParametricSweep,
    Parameter,
    ParameterDefinitions,
    PassFail,
    Pins,
    PinMapping,
    Plots,
    PowerBudgetOk,
    PowerCheck,
    Project,
    ProjectOverview,
    Properties,
    Recommendations,
    ReviewScore,
    Search,
    Severity,
    Signal,
    Signals,
    MoreSignals,
    Queued,
    QuickActions,
    Ready,
    Range,
    RecentMeasurements,
    RecentProjects,
    RecentRuns,
    RecommendedForYou,
    Renderer,
    ReportsCaption,
    ReportPreview,
    ReportBuilder,
    ReportTitle,
    ReportsResults,
    ResponseMeasurements,
    References,
    Run,
    RunContext,
    RunHint,
    RunSimulation,
    RunStatus,
    Running,
    Saved,
    Save,
    SaveHint,
    PassRate,
    SchematicHealth,
    SchematicInspectorCaption,
    SchematicTabs,
    SchematicTools,
    Selection,
    SelectionProperties,
    Settings,
    Sheets,
    Shortcuts,
    Simulator,
    Suggestions,
    SimulationQueue,
    SimulationOptions,
    SimulationSolver,
    SimulationSolverCaption,
    SimulationProfile,
    #[allow(dead_code)]
    SimulationProfileEditor,
    #[allow(dead_code)]
    SimulationOverview,
    SimulationWorkspace,
    SolverEngine,
    SolverHealth,
    Solver,
    SpiceModel,
    StabilityRisk,
    StatisticalSummary,
    StartSweep,
    StartTemplate,
    StatusConsole,
    StepSize,
    StudioSubtitle,
    StudioTitle,
    SuggestSimulations,
    Symbols,
    SymbolCoverage,
    SymbolDetails,
    SymbolLibrary,
    SymbolPreview,
    SystemOperational,
    System,
    TemplateDcDc,
    TemplateDifferentialPair,
    TemplateLdo,
    TemplateOpAmp,
    TemplatePowerSupply,
    Templates,
    Theme,
    Threads,
    TimeDomain,
    TemperatureSweep,
    Tolerance,
    StopTime,
    UnsavedChanges,
    Units,
    Update,
    Use,
    Uuid,
    VendorUpdates,
    Verified,
    VerifyStability,
    View,
    ViewAll,
    WorstMargin,
    WaveformAnalysis,
    WaveformAnalysisCaption,
    WaveformEmptyHint,
    WaveformError,
    WaveformViewer,
    Waveforms,
    EyeDiagram,
    Cursors,
    ComparisonManager,
    Compare,
    Completed,
    Points,
    RunStatistics,
    Rms,
    Samples,
    PeakToPeak,
    Wires,
    Workspace,
    Zoom,
    DocumentStructure,
    Down,
    Left,
    Right,
    Up,
    Validation,
    RunOutput,
    SetDirective,
    TotalMeasurements,
    TopRecommendations,
    OverallScore,
    WaveformInsight,
    Major,
    Minor,
    Critical,
    Yield,
}


include!("localization_en_impl.rs");
include!("localization_zh_impl.rs");

#[cfg(test)]
mod tests {
    use super::{StudioLocale, UiText};

    #[test]
    fn locales_have_stable_labels() {
        assert_eq!(StudioLocale::ALL.len(), 2);
        assert_eq!(StudioLocale::English.text(UiText::Settings), "Settings");
        assert_eq!(
            StudioLocale::SimplifiedChinese.text(UiText::Settings),
            "设置"
        );
    }
}
