#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub(super) enum StudioLocale {
    #[default]
    English,
    SimplifiedChinese,
}

impl StudioLocale {
    pub(super) const ALL: [Self; 2] = [Self::English, Self::SimplifiedChinese];

    pub(super) fn native_name(self) -> &'static str {
        match self {
            Self::English => "English",
            Self::SimplifiedChinese => "简体中文",
        }
    }

    pub(super) fn short_code(self) -> &'static str {
        match self {
            Self::English => "EN",
            Self::SimplifiedChinese => "中",
        }
    }

    pub(super) fn next(self) -> Self {
        match self {
            Self::English => Self::SimplifiedChinese,
            Self::SimplifiedChinese => Self::English,
        }
    }

    pub(super) fn text(self, key: UiText) -> &'static str {
        match self {
            Self::English => key.en(),
            Self::SimplifiedChinese => key.zh_hans(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(dead_code)]
pub(super) enum UiText {
    ActiveProject,
    AiAssistant,
    AnalysisStatus,
    AnalysisSetup,
    Appearance,
    Appendix,
    Artifacts,
    AskCircuit,
    AssistantPrompt,
    AutoScale,
    Average,
    Backend,
    BaselineRun,
    Body,
    BodePlot,
    Bounds,
    Buses,
    ApplyProperties,
    CanvasLinked,
    ComponentParameters,
    CandidateResults,
    Category,
    CheckLoopStability,
    Clean,
    CommandCenter,
    CoverPage,
    CrossProbe,
    CriticalFailures,
    Constraints,
    CurrentLanguage,
    CurrentTheme,
    Drc,
    DeleteSelected,
    Diagnostics,
    Dirty,
    Document,
    DesignChecklist,
    DesignReview,
    Distributions,
    Edit,
    ExplainWaveform,
    ExportReport,
    ExportCsv,
    ExportHistory,
    ExportShare,
    ExportWaveforms,
    Fit,
    FitHint,
    FindOptimization,
    FftAnalysis,
    FormulaEditor,
    Graphics,
    Groups,
    HealthReady,
    HighThd,
    HomeSubtitle,
    HomeTitle,
    ImportKiCad,
    ImportMeasurementData,
    Impact,
    Info,
    Insights,
    Inspector,
    JobMonitor,
    KiCadInspector,
    Kind,
    Label,
    LastRun,
    LastValue,
    Labels,
    Language,
    Libraries,
    LibrarySearchHint,
    LibraryScope,
    LibraryStatus,
    LiveMeasurements,
    LoadSymbols,
    LoopStability,
    Matches,
    MeasurementNoise,
    Measurements,
    Missing,
    ModelUpdateAvailable,
    ModelLibrary,
    ModelParameters,
    ModelLibraryCaption,
    ModelPreview,
    ModelSummary,
    MonteCarlo,
    MoreVariables,
    NewProject,
    NewSchematic,
    NoiseAnalysis,
    Issues,
    NoDiagnostics,
    NoDocument,
    NoEditableSchematicLoaded,
    NoLibraryLoaded,
    NoProject,
    NoRecentRun,
    NoSchematicLoaded,
    NoSelectedItem,
    NoSelection,
    NoWaveform,
    Netlist,
    NetlistPreview,
    NextSteps,
    OpenSchematic,
    OpenIssues,
    OpenProject,
    Optimization,
    OptimizationCaption,
    OptimizationStudio,
    Objective,
    OutputArtifacts,
    Overview,
    PageSize,
    ParametricSweep,
    Parameter,
    ParameterDefinitions,
    PassFail,
    Pins,
    PinMapping,
    Plots,
    PowerBudgetOk,
    PowerCheck,
    Project,
    ProjectOverview,
    Properties,
    Recommendations,
    ReviewScore,
    Search,
    Severity,
    Signal,
    Signals,
    MoreSignals,
    Queued,
    QuickActions,
    Ready,
    Range,
    RecentMeasurements,
    RecentProjects,
    RecentRuns,
    RecommendedForYou,
    Renderer,
    ReportsCaption,
    ReportPreview,
    ReportBuilder,
    ReportTitle,
    ReportsResults,
    ResponseMeasurements,
    References,
    Run,
    RunContext,
    RunHint,
    RunSimulation,
    RunStatus,
    Running,
    Saved,
    Save,
    SaveHint,
    PassRate,
    SchematicHealth,
    SchematicInspectorCaption,
    SchematicTabs,
    SchematicTools,
    Selection,
    SelectionProperties,
    Settings,
    Sheets,
    Shortcuts,
    Simulator,
    Suggestions,
    SimulationQueue,
    SimulationOptions,
    SimulationSolver,
    SimulationSolverCaption,
    SimulationProfile,
    #[allow(dead_code)]
    SimulationProfileEditor,
    #[allow(dead_code)]
    SimulationOverview,
    SimulationWorkspace,
    SolverEngine,
    SolverHealth,
    Solver,
    SpiceModel,
    StabilityRisk,
    StatisticalSummary,
    StartSweep,
    StartTemplate,
    StatusConsole,
    StepSize,
    StudioSubtitle,
    StudioTitle,
    SuggestSimulations,
    Symbols,
    SymbolCoverage,
    SymbolDetails,
    SymbolLibrary,
    SymbolPreview,
    SystemOperational,
    System,
    TemplateDcDc,
    TemplateDifferentialPair,
    TemplateLdo,
    TemplateOpAmp,
    TemplatePowerSupply,
    Templates,
    Theme,
    Threads,
    TimeDomain,
    TemperatureSweep,
    Tolerance,
    StopTime,
    UnsavedChanges,
    Units,
    Update,
    Use,
    Uuid,
    VendorUpdates,
    Verified,
    VerifyStability,
    View,
    ViewAll,
    WorstMargin,
    WaveformAnalysis,
    WaveformAnalysisCaption,
    WaveformEmptyHint,
    WaveformError,
    WaveformViewer,
    Waveforms,
    EyeDiagram,
    Cursors,
    ComparisonManager,
    Compare,
    Completed,
    Points,
    RunStatistics,
    Rms,
    Samples,
    PeakToPeak,
    Wires,
    Workspace,
    Zoom,
    DocumentStructure,
    Down,
    Left,
    Right,
    Up,
    Validation,
    RunOutput,
    SetDirective,
    TotalMeasurements,
    TopRecommendations,
    OverallScore,
    WaveformInsight,
    Major,
    Minor,
    Critical,
    Yield,
}

impl UiText {
    fn en(self) -> &'static str {
        match self {
            Self::ActiveProject => "Active Project",
            Self::AiAssistant => "AI Assistant",
            Self::AnalysisStatus => "Analysis Status",
            Self::AnalysisSetup => "Analysis Setup",
            Self::Appearance => "Appearance",
            Self::Appendix => "Appendix",
            Self::Artifacts => "Artifacts",
            Self::AskCircuit => "Ask anything about your circuit",
            Self::AssistantPrompt => "How can I help with the active schematic?",
            Self::AutoScale => "Auto Scale",
            Self::Average => "Average",
            Self::Backend => "Backend",
            Self::BaselineRun => "Run 1 (Baseline)",
            Self::Body => "Body",
            Self::BodePlot => "Bode Plot",
            Self::Bounds => "Bounds",
            Self::Buses => "Buses",
            Self::ApplyProperties => "Apply Properties",
            Self::CanvasLinked => "Canvas linked",
            Self::ComponentParameters => "Component Parameters",
            Self::CandidateResults => "Candidate Results",
            Self::Category => "Category",
            Self::CheckLoopStability => "Check loop stability",
            Self::Clean => "clean",
            Self::CommandCenter => "Command Center",
            Self::CoverPage => "Cover Page",
            Self::CrossProbe => "Cross Probe",
            Self::CriticalFailures => "Critical Failures",
            Self::Constraints => "Constraints",
            Self::CurrentLanguage => "Current language",
            Self::CurrentTheme => "Current theme",
            Self::Drc => "DRC",
            Self::DeleteSelected => "Delete Selected",
            Self::Diagnostics => "Diagnostics",
            Self::Dirty => "dirty",
            Self::Document => "Document",
            Self::DesignChecklist => "Op Amp Design Checklist",
            Self::DesignReview => "Design Review",
            Self::Distributions => "Distributions",
            Self::Edit => "Edit",
            Self::ExplainWaveform => "Explain this waveform",
            Self::ExportReport => "Export Report",
            Self::ExportCsv => "Export Data (CSV)",
            Self::ExportHistory => "Export History",
            Self::ExportShare => "Export & Share",
            Self::ExportWaveforms => "Export Waveforms",
            Self::Fit => "Fit",
            Self::FitHint => "Fit the schematic to the canvas",
            Self::FindOptimization => "Find optimization opportunities",
            Self::FftAnalysis => "FFT Analysis",
            Self::FormulaEditor => "Formula Editor",
            Self::Graphics => "Graphics",
            Self::Groups => "Groups",
            Self::HealthReady => "Ready",
            Self::HighThd => "High THD",
            Self::HomeSubtitle => "Design, simulate, and analyze with one Rust-native workflow.",
            Self::HomeTitle => "Welcome back",
            Self::ImportKiCad => "Import KiCad",
            Self::ImportMeasurementData => "Import Measurement Data",
            Self::Impact => "Impact",
            Self::Info => "info",
            Self::Insights => "Insights",
            Self::Inspector => "Inspector",
            Self::JobMonitor => "Job Monitor",
            Self::KiCadInspector => "KiCad Inspector",
            Self::Kind => "Kind",
            Self::Label => "Label",
            Self::LastRun => "Last run",
            Self::LastValue => "Last",
            Self::Labels => "Labels",
            Self::Language => "Language",
            Self::Libraries => "Libraries",
            Self::LibrarySearchHint => "Search KiCad symbols for placement",
            Self::LibraryScope => "Library Scope",
            Self::LibraryStatus => "Library Status",
            Self::LiveMeasurements => "Live Measurements",
            Self::LoadSymbols => "Load Symbols",
            Self::LoopStability => "Loop Stability",
            Self::Matches => "Matches",
            Self::MeasurementNoise => "Measurement Noise",
            Self::Measurements => "Measurements",
            Self::Missing => "missing",
            Self::ModelUpdateAvailable => "Model Update Available",
            Self::ModelLibrary => "Model Library",
            Self::ModelParameters => "Model Parameters",
            Self::ModelLibraryCaption => {
                "Search, compare, preview, and place KiCad-compatible symbols."
            }
            Self::ModelPreview => "Model Preview",
            Self::ModelSummary => "Model Summary",
            Self::MonteCarlo => "Monte Carlo",
            Self::MoreVariables => "more variables",
            Self::NewProject => "New Project",
            Self::NewSchematic => "New Schematic",
            Self::NoiseAnalysis => "Noise Analysis",
            Self::Issues => "Issues",
            Self::NoDiagnostics => "No diagnostics",
            Self::NoDocument => "No document",
            Self::NoEditableSchematicLoaded => "No editable schematic loaded",
            Self::NoLibraryLoaded => "No symbol library loaded",
            Self::NoProject => "No project",
            Self::NoRecentRun => "No recent run",
            Self::NoSchematicLoaded => "No schematic loaded",
            Self::NoSelectedItem => "No selected item",
            Self::NoSelection => "No selection",
            Self::NoWaveform => "No waveform",
            Self::Netlist => "Netlist",
            Self::NetlistPreview => "Netlist Preview",
            Self::NextSteps => "Next Steps",
            Self::OpenSchematic => "Open Schematic",
            Self::OpenIssues => "Open Issues",
            Self::OpenProject => "Open Project",
            Self::Optimization => "Optimization",
            Self::OptimizationCaption => {
                "Explore parameter sweeps, Monte Carlo yield, and optimization targets."
            }
            Self::OptimizationStudio => "Optimization Studio",
            Self::Objective => "Objective",
            Self::OutputArtifacts => "Output Artifacts",
            Self::Overview => "Overview",
            Self::PageSize => "Page Size",
            Self::ParametricSweep => "Parametric Sweep",
            Self::Parameter => "Parameter",
            Self::ParameterDefinitions => "Parameter Definitions",
            Self::PassFail => "Pass / Fail",
            Self::Pins => "Pins",
            Self::PinMapping => "Pin Mapping",
            Self::Plots => "Plots",
            Self::PowerBudgetOk => "Power budget within limits",
            Self::PowerCheck => "Power Check",
            Self::Project => "Project",
            Self::ProjectOverview => "Project Overview",
            Self::Properties => "Properties",
            Self::Recommendations => "Recommendations",
            Self::ReviewScore => "Review Score",
            Self::Signal => "Signal",
            Self::Signals => "Signals",
            Self::Severity => "Severity",
            Self::MoreSignals => "more signals",
            Self::Queued => "Queued",
            Self::QuickActions => "Quick Actions",
            Self::Ready => "Ready",
            Self::Range => "Range",
            Self::RecentMeasurements => "Recent Measurements",
            Self::RecentProjects => "Recent Projects",
            Self::RecentRuns => "Recent Runs",
            Self::RecommendedForYou => "Recommended For You",
            Self::Renderer => "Renderer",
            Self::ReportsCaption => {
                "Latest run artifacts, generated HTML reports, and waveform previews."
            }
            Self::ReportPreview => "Report Preview",
            Self::ReportBuilder => "Report Builder",
            Self::ReportTitle => "Report Title",
            Self::ReportsResults => "Reports & Results",
            Self::ResponseMeasurements => "Response / Measurements",
            Self::References => "References",
            Self::Run => "Run",
            Self::RunContext => "Run Context",
            Self::RunHint => "Run ngspice for the active schematic",
            Self::RunSimulation => "Run Simulation",
            Self::RunStatus => "Run Status",
            Self::Running => "Running",
            Self::Saved => "Saved",
            Self::Save => "Save",
            Self::SaveHint => "Save the active KiCad schematic",
            Self::PassRate => "Pass Rate",
            Self::SchematicHealth => "Schematic Health",
            Self::SchematicInspectorCaption => {
                "Edit selection, inspect KiCad data, libraries, and simulation context."
            }
            Self::SchematicTabs => "Schematic Tabs",
            Self::SchematicTools => "Schematic Tools",
            Self::Search => "Search",
            Self::Selection => "Selection",
            Self::SelectionProperties => "Selection Properties",
            Self::Settings => "Settings",
            Self::Sheets => "Sheets",
            Self::Shortcuts => "Shortcuts",
            Self::Simulator => "Simulator",
            Self::Suggestions => "Suggestions",
            Self::SimulationQueue => "Simulation Queue",
            Self::SimulationOptions => "Simulation Options",
            Self::SimulationOverview => "Overview",
            Self::SimulationProfileEditor => "Profile Editor",
            Self::SimulationSolver => "Simulation & Solver",
            Self::SimulationSolverCaption => {
                "Configure analyses, launch ngspice, and inspect generated run outputs."
            }
            Self::SimulationProfile => "Simulation Profile",
            Self::SimulationWorkspace => "Simulation Workspace",
            Self::SolverEngine => "Solver Engine",
            Self::SolverHealth => "System & Solver Health",
            Self::Solver => "Solver",
            Self::SpiceModel => "SPICE Model",
            Self::StabilityRisk => "Stability Risk",
            Self::StatisticalSummary => "Statistical Summary",
            Self::StartSweep => "Start Sweep",
            Self::StartTemplate => "Start from a Template",
            Self::StatusConsole => "Console",
            Self::StepSize => "Step Size",
            Self::StudioSubtitle => "Rust-native KiCad schematic and ngspice studio",
            Self::StudioTitle => "NekoSpice Studio",
            Self::SuggestSimulations => "Suggest simulations",
            Self::Symbols => "Symbols",
            Self::SymbolCoverage => "Symbol Coverage",
            Self::SymbolDetails => "Symbol Details",
            Self::SymbolLibrary => "Symbol Library",
            Self::SymbolPreview => "Symbol Preview",
            Self::SystemOperational => "All systems operational",
            Self::System => "System",
            Self::TemplateDcDc => "DC-DC Converter",
            Self::TemplateDifferentialPair => "Differential Pair",
            Self::TemplateLdo => "LDO Regulator",
            Self::TemplateOpAmp => "Operational Amplifier",
            Self::TemplatePowerSupply => "Switching Power Supply",
            Self::Templates => "Templates",
            Self::Theme => "Theme",
            Self::Threads => "Threads",
            Self::TimeDomain => "Time Domain",
            Self::TemperatureSweep => "Temperature Sweep",
            Self::Tolerance => "Tolerance",
            Self::StopTime => "Stop Time",
            Self::UnsavedChanges => "Unsaved changes",
            Self::Units => "Units",
            Self::Update => "Update",
            Self::Use => "Use",
            Self::Uuid => "UUID",
            Self::VerifyStability => "Verify Stability",
            Self::View => "View",
            Self::ViewAll => "View all",
            Self::WorstMargin => "Worst Margin",
            Self::WaveformAnalysis => "Waveform Analysis",
            Self::WaveformAnalysisCaption => {
                "Interactive analysis of simulation results with measurements and comparisons."
            }
            Self::WaveformEmptyHint => {
                "Run ngspice from the active schematic to generate waveform.raw."
            }
            Self::WaveformError => "Waveform error",
            Self::WaveformViewer => "Waveform Viewer",
            Self::Waveforms => "Waveforms",
            Self::EyeDiagram => "Eye Diagram",
            Self::Cursors => "Cursors",
            Self::ComparisonManager => "Comparison Manager",
            Self::Completed => "Completed",
            Self::Points => "Points",
            Self::RunStatistics => "Run Statistics",
            Self::Rms => "RMS",
            Self::Samples => "Samples",
            Self::PeakToPeak => "P-P",
            Self::Wires => "Wires",
            Self::Workspace => "Workspace",
            Self::Zoom => "Zoom",
            Self::DocumentStructure => "Document Structure",
            Self::Down => "Down",
            Self::Left => "Left",
            Self::Right => "Right",
            Self::Up => "Up",
            Self::Validation => "Validation",
            Self::VendorUpdates => "Vendor Updates",
            Self::Verified => "Verified",
            Self::Compare => "Compare",
            Self::RunOutput => "Run Output",
            Self::SetDirective => "Set Directive",
            Self::TotalMeasurements => "Total Measurements",
            Self::TopRecommendations => "Top Recommendations",
            Self::OverallScore => "Overall Score",
            Self::WaveformInsight => "Waveform Insight",
            Self::Major => "Major",
            Self::Minor => "Minor",
            Self::Critical => "Critical",
            Self::Yield => "Yield",
        }
    }

    fn zh_hans(self) -> &'static str {
        match self {
            Self::ActiveProject => "当前项目",
            Self::AiAssistant => "AI 助手",
            Self::AnalysisStatus => "分析状态",
            Self::AnalysisSetup => "分析设置",
            Self::Appearance => "外观",
            Self::Appendix => "附录",
            Self::Artifacts => "产物",
            Self::AskCircuit => "询问当前电路问题",
            Self::AssistantPrompt => "我可以怎样协助当前原理图？",
            Self::AutoScale => "自动缩放",
            Self::Average => "平均值",
            Self::Backend => "后端",
            Self::BaselineRun => "运行 1（基线）",
            Self::Body => "正文",
            Self::BodePlot => "波特图",
            Self::Bounds => "边界",
            Self::Buses => "总线",
            Self::ApplyProperties => "应用属性",
            Self::CanvasLinked => "画布已联动",
            Self::ComponentParameters => "元件参数",
            Self::CandidateResults => "候选结果",
            Self::Category => "类别",
            Self::CheckLoopStability => "检查环路稳定性",
            Self::Clean => "已保存",
            Self::CommandCenter => "指挥中心",
            Self::CoverPage => "封面",
            Self::CrossProbe => "交叉探查",
            Self::CriticalFailures => "关键失败",
            Self::Constraints => "约束",
            Self::CurrentLanguage => "当前语言",
            Self::CurrentTheme => "当前主题",
            Self::Drc => "DRC",
            Self::DeleteSelected => "删除选中项",
            Self::Diagnostics => "诊断",
            Self::Dirty => "未保存",
            Self::Document => "文档",
            Self::DesignChecklist => "运放设计检查清单",
            Self::DesignReview => "设计审查",
            Self::Distributions => "分布",
            Self::Edit => "编辑",
            Self::ExplainWaveform => "解释这个波形",
            Self::ExportReport => "导出报告",
            Self::ExportCsv => "导出数据 (CSV)",
            Self::ExportHistory => "导出历史",
            Self::ExportShare => "导出与分享",
            Self::ExportWaveforms => "导出波形",
            Self::Fit => "适配",
            Self::FitHint => "将原理图适配到画布",
            Self::FindOptimization => "查找优化机会",
            Self::FftAnalysis => "FFT 分析",
            Self::FormulaEditor => "公式编辑器",
            Self::Graphics => "图形",
            Self::Groups => "分组",
            Self::HealthReady => "就绪",
            Self::HighThd => "高 THD",
            Self::HomeSubtitle => "用 Rust 原生流程完成设计、仿真和分析。",
            Self::HomeTitle => "欢迎回来",
            Self::ImportKiCad => "导入 KiCad",
            Self::ImportMeasurementData => "导入测量数据",
            Self::Impact => "影响",
            Self::Info => "信息",
            Self::Insights => "洞察",
            Self::Inspector => "检查器",
            Self::JobMonitor => "作业监控",
            Self::KiCadInspector => "KiCad 检查器",
            Self::Kind => "类型",
            Self::Label => "标签",
            Self::LastRun => "上次运行",
            Self::LastValue => "末值",
            Self::Labels => "标签",
            Self::Language => "语言",
            Self::Libraries => "库",
            Self::LibrarySearchHint => "搜索 KiCad 符号用于放置",
            Self::LibraryScope => "库范围",
            Self::LibraryStatus => "库状态",
            Self::LiveMeasurements => "实时测量",
            Self::LoadSymbols => "加载符号",
            Self::LoopStability => "环路稳定性",
            Self::Matches => "匹配",
            Self::MeasurementNoise => "测量噪声",
            Self::Measurements => "测量",
            Self::Missing => "缺失",
            Self::ModelUpdateAvailable => "模型更新可用",
            Self::ModelLibrary => "模型库",
            Self::ModelParameters => "模型参数",
            Self::ModelLibraryCaption => "搜索、比较、预览并放置兼容 KiCad 的符号。",
            Self::ModelPreview => "模型预览",
            Self::ModelSummary => "模型摘要",
            Self::MonteCarlo => "蒙特卡洛",
            Self::MoreVariables => "个更多变量",
            Self::NewProject => "新建项目",
            Self::NewSchematic => "新建原理图",
            Self::NoiseAnalysis => "噪声分析",
            Self::Issues => "问题",
            Self::NoDiagnostics => "无诊断",
            Self::NoDocument => "无文档",
            Self::NoEditableSchematicLoaded => "未加载可编辑原理图",
            Self::NoLibraryLoaded => "未加载符号库",
            Self::NoProject => "无项目",
            Self::NoRecentRun => "暂无运行记录",
            Self::NoSchematicLoaded => "未加载原理图",
            Self::NoSelectedItem => "未选择项目",
            Self::NoSelection => "未选择",
            Self::NoWaveform => "无波形",
            Self::Netlist => "网表",
            Self::NetlistPreview => "网表预览",
            Self::NextSteps => "下一步",
            Self::OpenSchematic => "打开原理图",
            Self::OpenIssues => "待处理问题",
            Self::OpenProject => "打开项目",
            Self::Optimization => "优化",
            Self::OptimizationCaption => "探索参数扫描、蒙特卡洛良率和优化目标。",
            Self::OptimizationStudio => "优化工作台",
            Self::Objective => "目标",
            Self::OutputArtifacts => "输出产物",
            Self::Overview => "概览",
            Self::PageSize => "页面尺寸",
            Self::ParametricSweep => "参数扫描",
            Self::Parameter => "参数",
            Self::ParameterDefinitions => "参数定义",
            Self::PassFail => "通过 / 失败",
            Self::Pins => "引脚",
            Self::PinMapping => "引脚映射",
            Self::Plots => "图表",
            Self::PowerBudgetOk => "功耗预算在安全范围内",
            Self::PowerCheck => "功耗检查",
            Self::Project => "项目",
            Self::ProjectOverview => "项目概览",
            Self::Properties => "属性",
            Self::Recommendations => "建议",
            Self::ReviewScore => "审查评分",
            Self::Signal => "信号",
            Self::Signals => "信号",
            Self::Severity => "严重性",
            Self::MoreSignals => "个更多信号",
            Self::Queued => "排队中",
            Self::QuickActions => "快捷操作",
            Self::Ready => "就绪",
            Self::Range => "范围",
            Self::RecentMeasurements => "最近测量",
            Self::RecentProjects => "最近项目",
            Self::RecentRuns => "最近运行",
            Self::RecommendedForYou => "推荐操作",
            Self::Renderer => "渲染器",
            Self::ReportsCaption => "最近运行产物、HTML 报告和波形预览。",
            Self::ReportPreview => "报告预览",
            Self::ReportBuilder => "报告构建器",
            Self::ReportTitle => "报告标题",
            Self::ReportsResults => "报告与结果",
            Self::ResponseMeasurements => "响应 / 测量",
            Self::References => "参考",
            Self::Run => "运行",
            Self::RunContext => "运行上下文",
            Self::RunHint => "使用 ngspice 运行当前原理图",
            Self::RunSimulation => "运行仿真",
            Self::RunStatus => "运行状态",
            Self::Running => "运行中",
            Self::Saved => "已保存",
            Self::Save => "保存",
            Self::SaveHint => "保存当前 KiCad 原理图",
            Self::PassRate => "通过率",
            Self::SchematicHealth => "原理图概况",
            Self::SchematicInspectorCaption => "编辑选择项，检查 KiCad 数据、库和仿真上下文。",
            Self::SchematicTabs => "原理图标签",
            Self::SchematicTools => "原理图工具",
            Self::Search => "搜索",
            Self::Selection => "选择",
            Self::SelectionProperties => "选择项属性",
            Self::Settings => "设置",
            Self::Sheets => "图纸",
            Self::Shortcuts => "快捷入口",
            Self::Simulator => "仿真器",
            Self::Suggestions => "建议项",
            Self::SimulationQueue => "仿真队列",
            Self::SimulationOptions => "仿真选项",
            Self::SimulationOverview => "概览",
            Self::SimulationProfileEditor => "配置编辑器",
            Self::SimulationSolver => "仿真与求解器",
            Self::SimulationSolverCaption => "配置分析任务，启动 ngspice，并检查生成的运行输出。",
            Self::SimulationProfile => "仿真配置",
            Self::SimulationWorkspace => "仿真工作区",
            Self::SolverEngine => "求解器引擎",
            Self::SolverHealth => "系统与求解器状态",
            Self::Solver => "求解器",
            Self::SpiceModel => "SPICE 模型",
            Self::StabilityRisk => "稳定性风险",
            Self::StatisticalSummary => "统计摘要",
            Self::StartSweep => "开始扫描",
            Self::StartTemplate => "从模板开始",
            Self::StatusConsole => "控制台",
            Self::StepSize => "步长",
            Self::StudioSubtitle => "Rust 原生 KiCad 原理图与 ngspice 工作台",
            Self::StudioTitle => "NekoSpice 工作台",
            Self::SuggestSimulations => "建议仿真任务",
            Self::Symbols => "符号",
            Self::SymbolCoverage => "符号覆盖率",
            Self::SymbolDetails => "符号详情",
            Self::SymbolLibrary => "符号库",
            Self::SymbolPreview => "符号预览",
            Self::SystemOperational => "所有系统运行正常",
            Self::System => "系统",
            Self::TemplateDcDc => "DC-DC 转换器",
            Self::TemplateDifferentialPair => "差分对",
            Self::TemplateLdo => "LDO 稳压器",
            Self::TemplateOpAmp => "运算放大器",
            Self::TemplatePowerSupply => "开关电源",
            Self::Templates => "模板",
            Self::Theme => "主题",
            Self::Threads => "线程",
            Self::TimeDomain => "时域",
            Self::TemperatureSweep => "温度扫描",
            Self::Tolerance => "容差",
            Self::StopTime => "停止时间",
            Self::UnsavedChanges => "未保存更改",
            Self::Units => "单元",
            Self::Update => "更新",
            Self::Use => "使用",
            Self::Uuid => "UUID",
            Self::VerifyStability => "验证稳定性",
            Self::View => "查看",
            Self::ViewAll => "查看全部",
            Self::WorstMargin => "最差裕量",
            Self::WaveformAnalysis => "波形分析",
            Self::WaveformAnalysisCaption => "交互式分析仿真结果，管理测量和对比。",
            Self::WaveformEmptyHint => "从当前原理图运行 ngspice 以生成 waveform.raw。",
            Self::WaveformError => "波形错误",
            Self::WaveformViewer => "波形查看器",
            Self::Waveforms => "波形",
            Self::EyeDiagram => "眼图",
            Self::Cursors => "光标",
            Self::ComparisonManager => "对比管理",
            Self::Completed => "已完成",
            Self::Points => "点数",
            Self::RunStatistics => "运行统计",
            Self::Rms => "RMS",
            Self::Samples => "样本",
            Self::PeakToPeak => "峰峰值",
            Self::Wires => "导线",
            Self::Workspace => "工作区",
            Self::Zoom => "缩放",
            Self::DocumentStructure => "文档结构",
            Self::Down => "下",
            Self::Left => "左",
            Self::Right => "右",
            Self::Up => "上",
            Self::Validation => "验证",
            Self::VendorUpdates => "厂商更新",
            Self::Verified => "已验证",
            Self::Compare => "对比",
            Self::RunOutput => "运行输出",
            Self::SetDirective => "设置指令",
            Self::TotalMeasurements => "测量总数",
            Self::TopRecommendations => "重点建议",
            Self::OverallScore => "总评分",
            Self::WaveformInsight => "波形洞察",
            Self::Major => "主要",
            Self::Minor => "轻微",
            Self::Critical => "严重",
            Self::Yield => "良率",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{StudioLocale, UiText};

    #[test]
    fn locales_have_stable_labels() {
        assert_eq!(StudioLocale::ALL.len(), 2);
        assert_eq!(StudioLocale::English.text(UiText::Settings), "Settings");
        assert_eq!(
            StudioLocale::SimplifiedChinese.text(UiText::Settings),
            "设置"
        );
    }
}
