#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub(super) enum StudioLocale {
    #[default]
    English,
    SimplifiedChinese,
}

impl StudioLocale {
    pub(super) const ALL: [Self; 2] = [Self::English, Self::SimplifiedChinese];

    pub(super) fn native_name(self) -> &'static str {
        match self {
            Self::English => "English",
            Self::SimplifiedChinese => "简体中文",
        }
    }

    pub(super) fn short_code(self) -> &'static str {
        match self {
            Self::English => "EN",
            Self::SimplifiedChinese => "中",
        }
    }

    pub(super) fn next(self) -> Self {
        match self {
            Self::English => Self::SimplifiedChinese,
            Self::SimplifiedChinese => Self::English,
        }
    }

    pub(super) fn text(self, key: UiText) -> &'static str {
        match self {
            Self::English => key.en(),
            Self::SimplifiedChinese => key.zh_hans(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum UiText {
    ActiveProject,
    AiAssistant,
    Appearance,
    AskCircuit,
    AssistantPrompt,
    Average,
    Backend,
    Buses,
    CheckLoopStability,
    Clean,
    CurrentLanguage,
    CurrentTheme,
    Drc,
    DeleteSelected,
    Diagnostics,
    Dirty,
    Document,
    DesignChecklist,
    Edit,
    EditCommands,
    ExplainWaveform,
    Fit,
    FitHint,
    FindOptimization,
    Graphics,
    HealthReady,
    HighThd,
    HomeSubtitle,
    HomeTitle,
    ImportKiCad,
    ImportMeasurementData,
    Info,
    Insights,
    Inspector,
    Kind,
    Labels,
    Language,
    LibraryScope,
    LoopStability,
    MeasurementNoise,
    Missing,
    ModelUpdateAvailable,
    MonteCarlo,
    NewProject,
    NewSchematic,
    NoDiagnostics,
    NoDocument,
    NoEditableSchematicLoaded,
    NoProject,
    NoRecentRun,
    NoSchematicLoaded,
    NoSelectedItem,
    NoSelection,
    NoWaveform,
    Netlist,
    OpenSchematic,
    OpenProject,
    Optimization,
    ParametricSweep,
    PowerBudgetOk,
    PowerCheck,
    Project,
    ProjectOverview,
    Queued,
    QuickActions,
    Ready,
    RecentMeasurements,
    RecentProjects,
    RecommendedForYou,
    Renderer,
    ReportsCaption,
    ReportsResults,
    Run,
    RunHint,
    RunSimulation,
    Running,
    Saved,
    Save,
    SaveHint,
    SchematicHealth,
    SchematicTabs,
    SchematicTools,
    SchematicToolsCaption,
    Selection,
    Settings,
    Sheets,
    Shortcuts,
    SimulationQueue,
    SolverHealth,
    Solver,
    StabilityRisk,
    StartTemplate,
    StatusConsole,
    StudioSubtitle,
    StudioTitle,
    SuggestSimulations,
    Symbols,
    SystemOperational,
    System,
    TemplateDcDc,
    TemplateDifferentialPair,
    TemplateLdo,
    TemplateOpAmp,
    TemplatePowerSupply,
    Theme,
    Threads,
    TemperatureSweep,
    UnsavedChanges,
    Update,
    Use,
    VerifyStability,
    View,
    ViewAll,
    WaveformError,
    WaveformViewer,
    Waveforms,
    Wires,
    Workspace,
    Zoom,
}

impl UiText {
    fn en(self) -> &'static str {
        match self {
            Self::ActiveProject => "Active Project",
            Self::AiAssistant => "AI Assistant",
            Self::Appearance => "Appearance",
            Self::AskCircuit => "Ask anything about your circuit",
            Self::AssistantPrompt => "How can I help with the active schematic?",
            Self::Average => "Average",
            Self::Backend => "Backend",
            Self::Buses => "Buses",
            Self::CheckLoopStability => "Check loop stability",
            Self::Clean => "clean",
            Self::CurrentLanguage => "Current language",
            Self::CurrentTheme => "Current theme",
            Self::Drc => "DRC",
            Self::DeleteSelected => "Delete Selected",
            Self::Diagnostics => "Diagnostics",
            Self::Dirty => "dirty",
            Self::Document => "Document",
            Self::DesignChecklist => "Op Amp Design Checklist",
            Self::Edit => "Edit",
            Self::EditCommands => "Edit Commands",
            Self::ExplainWaveform => "Explain this waveform",
            Self::Fit => "Fit",
            Self::FitHint => "Fit the schematic to the canvas",
            Self::FindOptimization => "Find optimization opportunities",
            Self::Graphics => "Graphics",
            Self::HealthReady => "Ready",
            Self::HighThd => "High THD",
            Self::HomeSubtitle => "Design, simulate, and analyze with one Rust-native workflow.",
            Self::HomeTitle => "Welcome back",
            Self::ImportKiCad => "Import KiCad",
            Self::ImportMeasurementData => "Import Measurement Data",
            Self::Info => "info",
            Self::Insights => "Insights",
            Self::Inspector => "Inspector",
            Self::Kind => "Kind",
            Self::Labels => "Labels",
            Self::Language => "Language",
            Self::LibraryScope => "Library Scope",
            Self::LoopStability => "Loop Stability",
            Self::MeasurementNoise => "Measurement Noise",
            Self::Missing => "missing",
            Self::ModelUpdateAvailable => "Model Update Available",
            Self::MonteCarlo => "Monte Carlo",
            Self::NewProject => "New Project",
            Self::NewSchematic => "New Schematic",
            Self::NoDiagnostics => "No diagnostics",
            Self::NoDocument => "No document",
            Self::NoEditableSchematicLoaded => "No editable schematic loaded",
            Self::NoProject => "No project",
            Self::NoRecentRun => "No recent run",
            Self::NoSchematicLoaded => "No schematic loaded",
            Self::NoSelectedItem => "No selected item",
            Self::NoSelection => "No selection",
            Self::NoWaveform => "No waveform",
            Self::Netlist => "Netlist",
            Self::OpenSchematic => "Open Schematic",
            Self::OpenProject => "Open Project",
            Self::Optimization => "Optimization",
            Self::ParametricSweep => "Parametric Sweep",
            Self::PowerBudgetOk => "Power budget within limits",
            Self::PowerCheck => "Power Check",
            Self::Project => "Project",
            Self::ProjectOverview => "Project Overview",
            Self::Queued => "Queued",
            Self::QuickActions => "Quick Actions",
            Self::Ready => "Ready",
            Self::RecentMeasurements => "Recent Measurements",
            Self::RecentProjects => "Recent Projects",
            Self::RecommendedForYou => "Recommended For You",
            Self::Renderer => "Renderer",
            Self::ReportsCaption => {
                "Latest run artifacts, generated HTML reports, and waveform previews."
            }
            Self::ReportsResults => "Reports & Results",
            Self::Run => "Run",
            Self::RunHint => "Run ngspice for the active schematic",
            Self::RunSimulation => "Run Simulation",
            Self::Running => "Running",
            Self::Saved => "Saved",
            Self::Save => "Save",
            Self::SaveHint => "Save the active KiCad schematic",
            Self::SchematicHealth => "Schematic Health",
            Self::SchematicTabs => "Schematic Tabs",
            Self::SchematicTools => "Schematic Tools",
            Self::SchematicToolsCaption => "Place wires, labels, buses, sheets, and markers.",
            Self::Selection => "Selection",
            Self::Settings => "Settings",
            Self::Sheets => "Sheets",
            Self::Shortcuts => "Shortcuts",
            Self::SimulationQueue => "Simulation Queue",
            Self::SolverHealth => "System & Solver Health",
            Self::Solver => "Solver",
            Self::StabilityRisk => "Stability Risk",
            Self::StartTemplate => "Start from a Template",
            Self::StatusConsole => "Console",
            Self::StudioSubtitle => "Rust-native KiCad schematic and ngspice studio",
            Self::StudioTitle => "NekoSpice Studio",
            Self::SuggestSimulations => "Suggest simulations",
            Self::Symbols => "Symbols",
            Self::SystemOperational => "All systems operational",
            Self::System => "System",
            Self::TemplateDcDc => "DC-DC Converter",
            Self::TemplateDifferentialPair => "Differential Pair",
            Self::TemplateLdo => "LDO Regulator",
            Self::TemplateOpAmp => "Operational Amplifier",
            Self::TemplatePowerSupply => "Switching Power Supply",
            Self::Theme => "Theme",
            Self::Threads => "Threads",
            Self::TemperatureSweep => "Temperature Sweep",
            Self::UnsavedChanges => "Unsaved changes",
            Self::Update => "Update",
            Self::Use => "Use",
            Self::VerifyStability => "Verify Stability",
            Self::View => "View",
            Self::ViewAll => "View all",
            Self::WaveformError => "Waveform error",
            Self::WaveformViewer => "Waveform Viewer",
            Self::Waveforms => "Waveforms",
            Self::Wires => "Wires",
            Self::Workspace => "Workspace",
            Self::Zoom => "Zoom",
        }
    }

    fn zh_hans(self) -> &'static str {
        match self {
            Self::ActiveProject => "当前项目",
            Self::AiAssistant => "AI 助手",
            Self::Appearance => "外观",
            Self::AskCircuit => "询问当前电路问题",
            Self::AssistantPrompt => "我可以怎样协助当前原理图？",
            Self::Average => "平均值",
            Self::Backend => "后端",
            Self::Buses => "总线",
            Self::CheckLoopStability => "检查环路稳定性",
            Self::Clean => "已保存",
            Self::CurrentLanguage => "当前语言",
            Self::CurrentTheme => "当前主题",
            Self::Drc => "DRC",
            Self::DeleteSelected => "删除选中项",
            Self::Diagnostics => "诊断",
            Self::Dirty => "未保存",
            Self::Document => "文档",
            Self::DesignChecklist => "运放设计检查清单",
            Self::Edit => "编辑",
            Self::EditCommands => "编辑命令",
            Self::ExplainWaveform => "解释这个波形",
            Self::Fit => "适配",
            Self::FitHint => "将原理图适配到画布",
            Self::FindOptimization => "查找优化机会",
            Self::Graphics => "图形",
            Self::HealthReady => "就绪",
            Self::HighThd => "高 THD",
            Self::HomeSubtitle => "用 Rust 原生流程完成设计、仿真和分析。",
            Self::HomeTitle => "欢迎回来",
            Self::ImportKiCad => "导入 KiCad",
            Self::ImportMeasurementData => "导入测量数据",
            Self::Info => "信息",
            Self::Insights => "洞察",
            Self::Inspector => "检查器",
            Self::Kind => "类型",
            Self::Labels => "标签",
            Self::Language => "语言",
            Self::LibraryScope => "库范围",
            Self::LoopStability => "环路稳定性",
            Self::MeasurementNoise => "测量噪声",
            Self::Missing => "缺失",
            Self::ModelUpdateAvailable => "模型更新可用",
            Self::MonteCarlo => "蒙特卡洛",
            Self::NewProject => "新建项目",
            Self::NewSchematic => "新建原理图",
            Self::NoDiagnostics => "无诊断",
            Self::NoDocument => "无文档",
            Self::NoEditableSchematicLoaded => "未加载可编辑原理图",
            Self::NoProject => "无项目",
            Self::NoRecentRun => "暂无运行记录",
            Self::NoSchematicLoaded => "未加载原理图",
            Self::NoSelectedItem => "未选择项目",
            Self::NoSelection => "未选择",
            Self::NoWaveform => "无波形",
            Self::Netlist => "网表",
            Self::OpenSchematic => "打开原理图",
            Self::OpenProject => "打开项目",
            Self::Optimization => "优化",
            Self::ParametricSweep => "参数扫描",
            Self::PowerBudgetOk => "功耗预算在安全范围内",
            Self::PowerCheck => "功耗检查",
            Self::Project => "项目",
            Self::ProjectOverview => "项目概览",
            Self::Queued => "排队中",
            Self::QuickActions => "快捷操作",
            Self::Ready => "就绪",
            Self::RecentMeasurements => "最近测量",
            Self::RecentProjects => "最近项目",
            Self::RecommendedForYou => "推荐操作",
            Self::Renderer => "渲染器",
            Self::ReportsCaption => "最近运行产物、HTML 报告和波形预览。",
            Self::ReportsResults => "报告与结果",
            Self::Run => "运行",
            Self::RunHint => "使用 ngspice 运行当前原理图",
            Self::RunSimulation => "运行仿真",
            Self::Running => "运行中",
            Self::Saved => "已保存",
            Self::Save => "保存",
            Self::SaveHint => "保存当前 KiCad 原理图",
            Self::SchematicHealth => "原理图概况",
            Self::SchematicTabs => "原理图标签",
            Self::SchematicTools => "原理图工具",
            Self::SchematicToolsCaption => "放置导线、标签、总线、层级图纸和标记。",
            Self::Selection => "选择",
            Self::Settings => "设置",
            Self::Sheets => "图纸",
            Self::Shortcuts => "快捷入口",
            Self::SimulationQueue => "仿真队列",
            Self::SolverHealth => "系统与求解器状态",
            Self::Solver => "求解器",
            Self::StabilityRisk => "稳定性风险",
            Self::StartTemplate => "从模板开始",
            Self::StatusConsole => "控制台",
            Self::StudioSubtitle => "Rust 原生 KiCad 原理图与 ngspice 工作台",
            Self::StudioTitle => "NekoSpice 工作台",
            Self::SuggestSimulations => "建议仿真任务",
            Self::Symbols => "符号",
            Self::SystemOperational => "所有系统运行正常",
            Self::System => "系统",
            Self::TemplateDcDc => "DC-DC 转换器",
            Self::TemplateDifferentialPair => "差分对",
            Self::TemplateLdo => "LDO 稳压器",
            Self::TemplateOpAmp => "运算放大器",
            Self::TemplatePowerSupply => "开关电源",
            Self::Theme => "主题",
            Self::Threads => "线程",
            Self::TemperatureSweep => "温度扫描",
            Self::UnsavedChanges => "未保存更改",
            Self::Update => "更新",
            Self::Use => "使用",
            Self::VerifyStability => "验证稳定性",
            Self::View => "查看",
            Self::ViewAll => "查看全部",
            Self::WaveformError => "波形错误",
            Self::WaveformViewer => "波形查看器",
            Self::Waveforms => "波形",
            Self::Wires => "导线",
            Self::Workspace => "工作区",
            Self::Zoom => "缩放",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{StudioLocale, UiText};

    #[test]
    fn locales_have_stable_labels() {
        assert_eq!(StudioLocale::ALL.len(), 2);
        assert_eq!(StudioLocale::English.text(UiText::Settings), "Settings");
        assert_eq!(
            StudioLocale::SimplifiedChinese.text(UiText::Settings),
            "设置"
        );
    }
}
