Version 4
SymbolType BLOCK
PIN 0 0 LEFT 8
PINATTR PinName IN+
PINATTR SpiceOrder 1
PIN 0 16 LEFT 8
PINATTR PinName IN-
PINATTR SpiceOrder 2
PIN 64 8 RIGHT 8
PINATTR PinName OUT
PINATTR SpiceOrder 3
PIN 32 -24 TOP 8
PINATTR PinName VCC
PINATTR SpiceOrder 4
PIN 32 40 BOTTOM 8
PINATTR PinName VEE
PINATTR SpiceOrder 5
SYMATTR Prefix X
SYMATTR Value GOODAMP
